### PR TITLE
Add startOf, plus, fromMillis, valueOf methods

### PR DESCRIPTION
**Pull request by Thomas0c**
First of all I'd like to say - great initiative. I'd love to see luxon w. full Reason bindings.
Added a few more methods since I needed them for a project.

One thing to note is how `fromMillis` has a signature of `float -> t` instead of `int -> t`, this is due to the integer limits in ReasonML and the long int nature of epochs, e.g. `1515790145892`. `valueOf` has also been setup to return a float, so the two play nicely together, which is similar to luxon's `fromMillis` and `valueOf` methods.

Let me know any feedback/thoughts.

### CODE REVIEW

**Comment by davidgomes** [comment]
Great diff! Thank you for the contribution. I too want to complete the bindings.

Can you just run `refmt` on all the files you changed before we merge this?

**Comment by Thomas0c** [comment]
`refmt` has been run on all of the files already - I have it set up to do so automatically on file save. Just double-checked and there's no change compared to what has been committed.

**Comment by davidgomes** [comment]
You might want to update your refmt version then.

```
refmt --version
Reason 3.0.4 @ 731e605
```

This is mine, you can update by running:

```
# Mac
npm install -g https://github.com/reasonml/reason-cli/archive/3.0.4-bin-darwin.tar.gz
# Linux
npm install -g https://github.com/reasonml/reason-cli/archive/3.0.4-bin-linux.tar.gz
```

**Comment by Thomas0c** [comment]
Good call. Updated `refmt` and pushed updated files. See b97d7ec.

**Comment by davidgomes** [comment]
Great stuff!

**Pull request merged**
